spring:
  profiles:
    active: dev

server:
  port: 8080

mybatis-plus:
  global-config:
    banner: false
    db-config:
      id-type: auto

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ""

logging:
  level:
    root: warn

# mybatis的日志信息
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
#生产环境
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=Shanghai&?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ""
